### ISSUE TITLE
Check strict mode of sendApi()

### ISSUE THREAD

**Issue by cimfalab** [devjiro76/error-trace#1]
Dear,
I just checked errortracer.js code in my static analyzer. (https://deepscan.io/demo/)
It tells sendApi() can have a problem that `this` is undefined in strict mode.
![image](https://user-images.githubusercontent.com/762690/41764501-47091652-763c-11e8-9134-ab3ac7f56ffc.png)

ES6 module is implicitly in strict mode and the bundled file has 'use strict' explicitly.

So I ran a basic code in the browser and `this.apiURL` can't be accessed because `this` is undefined.
I think `sendApi()` should have `apiURL` as its parameter instead of accessing `this`.
Please check :)

```
<button id="triggerError">triggerError</button>

<script src="errortracer.bundle.js"></script>

<script>
  document.querySelector("#triggerError")
    .addEventListener("click", function () {
      notExist(); // make Error
    });

  const url = "http://xxxx..."; // Your Zapier Webhook URL

  new ErrorTracer({
    apiURL: url,
  });

  // or simpley
  new ErrorTracer(url);
</script>
```

**Comment by devjiro76** [comment]
Very thanks for your kind feedback. 👍 

There were two option for this issue.
1. using "bind"
2. using "send a parameter" (as you recommended)

I think second way is better to define private method's purpose,
so I followed your recommendation.

![image](https://user-images.githubusercontent.com/25057349/41787662-14a3c52a-7684-11e8-92c7-5236b4dd0066.png)

Thanks again and have a look.
Any feedback will be welcome.

**Comment by cimfalab** [comment]
I tried and checked that 'apiURL' is properly passed into '_sendApi'.
Thank you for your quickest fix :thumbsup: and badge :heart:
